Set up minimal testing for windows, macos, ubuntu; run examples on ubuntu w/ oldest support python only

diff --git a/.github/workflows/continuous-integration-workflow.yaml b/.github/workflows/continuous-integration-workflow.yaml
--- a/.github/workflows/continuous-integration-workflow.yaml
+++ b/.github/workflows/continuous-integration-workflow.yaml
@@ -25,11 +25,21 @@ jobs:
         python -m pip install --upgrade pip
         pip install ".[develop]"
     - uses: pre-commit/action@v3.0.0
-    - name: Run tests
-      if: success() || failure()  # Run this step even if the linting step fails
+    - name: Run tests (ubuntu, macos)
+      if: matrix.os != 'windows-latest' && (success() || failure())  # Run this step even if the linting step fails
       run: |
         mkdir -p temp1/temp2/temp3
         cp -rL tests temp1/temp2/temp3/.
+        cd temp1/temp2/temp3/
+
+        # -rA displays the captured output for all tests after they're run
+        # See the docs: https://doc.pytest.org/en/latest/reference/reference.html#command-line-flags
+        pytest -rA tests/ --ignore tests/timing.py --ignore tests/profiling.py
+    - name: Run tests (windows)
+      if: matrix.os == 'windows-latest' && (success() || failure())  # Run this step even if the linting step fails
+      run: |
+        mkdir -p temp1/temp2/temp3
+        cp -r tests temp1/temp2/temp3/.
         cd temp1/temp2/temp3/
 
         # -rA displays the captured output for all tests after they're run
